/**
 * Supabase Client (server-side only)
 *
 * Used for:
 * - Generating signed upload URLs for client-side direct uploads
 * - Downloading files from Supabase Storage for server-side processing
 *
 * The client-side never talks to Supabase directly — it uses signed URLs
 * generated by the server, so only the service key is needed.
 */

import { createClient, SupabaseClient } from "@supabase/supabase-js";

// Strip trailing whitespace/newlines that Vercel sometimes injects
const SUPABASE_URL = (process.env.SUPABASE_URL || "").replace(/[\s\\n]+$/g, "").replace(/\\n$/, "");
const SUPABASE_SERVICE_KEY = (process.env.SUPABASE_SERVICE_KEY || "").replace(/[\s\\n]+$/g, "").replace(/\\n$/, "");

export const MANUSCRIPTS_BUCKET = "manuscripts";

let _client: SupabaseClient | null = null;

/**
 * Get the server-side Supabase client (singleton).
 * Throws if SUPABASE_URL or SUPABASE_SERVICE_KEY are not configured.
 */
export function getSupabaseAdmin(): SupabaseClient {
  if (_client) return _client;

  if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) {
    throw new Error(
      "Supabase is not configured. Set SUPABASE_URL and SUPABASE_SERVICE_KEY environment variables."
    );
  }

  _client = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY, {
    auth: { persistSession: false },
  });

  return _client;
}

/**
 * Check whether Supabase Storage is available.
 */
export function isSupabaseConfigured(): boolean {
  return !!(SUPABASE_URL && SUPABASE_SERVICE_KEY);
}

/**
 * Generate a signed upload URL for the manuscripts bucket.
 * The client can PUT a file to this URL without needing any Supabase credentials.
 *
 * @param storagePath  Path within the bucket, e.g. "pub123/ms456/file.pdf"
 * @param expiresIn    Seconds until the URL expires (default 600 = 10 min)
 */
export async function createSignedUploadUrl(
  storagePath: string,
  expiresIn = 600
): Promise<{ signedUrl: string; token: string }> {
  const supabase = getSupabaseAdmin();

  const { data, error } = await supabase.storage
    .from(MANUSCRIPTS_BUCKET)
    .createSignedUploadUrl(storagePath);

  if (error || !data) {
    console.error("[Supabase] Failed to create signed upload URL:", error);
    throw new Error(`Failed to create upload URL: ${error?.message || "unknown error"}`);
  }

  return { signedUrl: data.signedUrl, token: data.token };
}

/**
 * Download a file from the manuscripts bucket as a Buffer.
 */
export async function downloadFile(storagePath: string): Promise<Buffer> {
  const supabase = getSupabaseAdmin();

  const { data, error } = await supabase.storage
    .from(MANUSCRIPTS_BUCKET)
    .download(storagePath);

  if (error || !data) {
    console.error("[Supabase] Failed to download file:", error);
    throw new Error(`Failed to download file: ${error?.message || "unknown error"}`);
  }

  // data is a Blob — convert to Buffer
  const arrayBuffer = await data.arrayBuffer();
  return Buffer.from(arrayBuffer);
}

/**
 * Delete a file from the manuscripts bucket.
 */
export async function deleteFile(storagePath: string): Promise<void> {
  const supabase = getSupabaseAdmin();

  const { error } = await supabase.storage
    .from(MANUSCRIPTS_BUCKET)
    .remove([storagePath]);

  if (error) {
    console.error("[Supabase] Failed to delete file:", error);
    // Don't throw — deletion failures are non-critical
  }
}

/**
 * Ensure the manuscripts bucket exists. Call once at startup or deploy.
 */
export async function ensureBucketExists(): Promise<void> {
  const supabase = getSupabaseAdmin();

  const { data: buckets } = await supabase.storage.listBuckets();
  const exists = buckets?.some((b) => b.name === MANUSCRIPTS_BUCKET);

  if (!exists) {
    const { error } = await supabase.storage.createBucket(MANUSCRIPTS_BUCKET, {
      public: false,
      fileSizeLimit: 52428800, // 50 MB
      allowedMimeTypes: [
        "application/pdf",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      ],
    });
    if (error) {
      console.error("[Supabase] Failed to create bucket:", error);
      throw new Error(`Failed to create manuscripts bucket: ${error.message}`);
    }
    console.log("[Supabase] Created 'manuscripts' bucket");
  }
}
