/**
 * Author-facing letter phrases for the iScience profile, keyed by the id suffix
 * of the FormatCheck ("iscience." + key). Each phrase is copied verbatim from the
 * editor's pre-accept letter maker spreadsheet (column "phrase"), including the
 * leading "* ", so the assembled letter looks exactly like the hand-made one.
 *
 * Two deliberate departures from the spreadsheet, both driven by the current
 * iScience Final File Requirements (FFC):
 *   - "references.entries": the spreadsheet still asks for Harvard-style in-text
 *     citations; the FFC now requires superscript numbers and a DOI per entry, so
 *     that paragraph is rewritten to match the FFC.
 *   - Phrases in FFC_PHRASES cover FFC rules that have no spreadsheet row.
 *
 * Header rows of the spreadsheet (RESOURCE AVAILABILITY, EXPERIMENTAL MODEL AND
 * SUBJECT DETAILS, METHODS DETAILS, QUANTIFICATION AND STATISTICAL ANALYSIS,
 * ADDITIONAL RESOURCES, KEY RESOURCES TABLE) are categories, not checks, and have
 * no phrase here.
 */

export const SPREADSHEET_QUESTIONS: Record<string, { row: number; question: string }> = {
  "file.word": { row: 3, question: "Is the main manuscript file a pdf?" },
  "title.length": { row: 4, question: "Does the title need to be edited (more than 12 words, more than 3 rows, more than 150 characters with spaces, containing punctuation)?" },
  "summary.editor_edits": { row: 5, question: "Does the summary need to be edited by you?" },
  "summary.length": { row: 6, question: "Does the summary need to be edited by the authors? (more than 150 words, missing background, description of results, indication of broader significance, has novelty claims, contains refernces)?" },
  "sections.order": { row: 7, question: "Is the manuscript lacking Introduction, Results and Discussion, Limitation of the study sections?" },
  "sections.limitations": { row: 8, question: "Is there a Limitations of the study section?" },
  "body.novelty": { row: 9, question: "Does the text contain excessive use of the words \"novel\", \"new\", \"first time\"" },
  "body.results_subheadings": { row: 10, question: "Is the results section lacking subdivisions?" },
  "body.personal_communication": { row: 11, question: "Are there references to \"personal communicaton\", or \"unpublished data\"?" },
  "tables.format": { row: 12, question: "Are there any tables? If yes are they in the correct format?" },
  "body.nomenclature": { row: 13, question: "Is nomenclature of genes/chemical compound adequate?" },
  "associated.highlights": { row: 14, question: "Are the highlight present? Are they no more than 4 and containing no more than 85 characters including spaces?" },
  "associated.graphical_abstract": { row: 15, question: "Is there a graphical abstract?" },
  "supplemental.figure_count": { row: 16, question: "Are the Supplementary info appropriate (number of figures, refrences etc)?" },
  "supplemental.related_to": { row: 17, question: "Are Supp. Info. items referencing the related main-text item or STAR Methods?" },
  "star.as_described_previously": { row: 18, question: "Is \"as described previously\" used in the Methods?" },
  "ethics.vertebrates": { row: 19, question: "Are there experiments with vertebrates?" },
  "ethics.humans": { row: 20, question: "Are there experiments with humans?" },
  "references.entries": { row: 21, question: "Are the references correctly formatted?" },
  "statements.acknowledgments": { row: 22, question: "Is there an acknowledgements section?" },
  "statements.author_contributions": { row: 23, question: "Is there an author contributions section?" },
  "statements.declaration_of_interests": { row: 24, question: "Is there a declaration of interest statement?" },
  "figures.separate_files": { row: 25, question: "Are figures not supplied as separate files in an appopriate format?" },
  "figures.error_bars": { row: 26, question: "Are there graphs with error bars?" },
  "figures.asterisks": { row: 27, question: "Are there statistical tests in the figures?" },
  "figures.scale_bars": { row: 28, question: "Are there images requiring scale bars?" },
  "figures.blot_markers": { row: 29, question: "Are there blots or gels?" },
  "data.supplementary_software": { row: 30, question: "Is there supplementary software" },
  "data.structures": { row: 31, question: "Does the paper present a novel protein structure?" },
  "data.gene_sequences": { row: 32, question: "Does the paper present novel gene sequences?" },
  "data.proteomics": { row: 33, question: "Does the paper present a proteomics dataset?" },
  "data.microarray": { row: 34, question: "Does the paper present microarray data?" },
  "data.rnaseq": { row: 35, question: "Does the paper present RNAseq data?" },
  "body.novel_compounds": { row: 36, question: "Does the paper contain structurally novel compounds?" },
  "body.equations": { row: 37, question: "Does the manuscript contain mathematical formulae?" },
  "supplemental.excel_tables": { row: 38, question: "Are there tables exceeding 3 pages?" },
  "supplemental.videos": { row: 39, question: "Are there any video?" },
  "associated.star_protocols": { row: 40, question: "Is there a Protocol protocol that should be considered for STAR Protocols stemming from this paper" },
  "statements.inclusion_diversity": { row: 41, question: "Is there an Inclusion and Diversity statement?" },
  "body.batteries_pv": { row: 42, question: "Are there any batteries or PV?" },
  "body.devices": { row: 43, question: "Are there any devices" },
  "star.present": { row: 44, question: "Is the entire STAR method missing?" },
  "star.headings_order": { row: 46, question: "Are the standard section present and in the right order? (RESOURCE AVAILABILITY; EXPERIMENTAL MODEL AND SUBJECT DETAILS; METHOD DETAILS; QUANTIFICATION AND STATISTICAL ANALYSIS; ADDITIONAL RESOURCES)" },
  "star.subheadings": { row: 47, question: "Are the subheadings absent, numbered, or too intricate?" },
  "star.references_in_lieu": { row: 48, question: "References without details" },
  "star.separate_reference_list": { row: 49, question: "Is there Separate reference list for STAR Methods and/or KRT?" },
  "star.complex_tables": { row: 50, question: "Are there any complex embedded tables?" },
  "star.numbered_tables": { row: 51, question: "Are there any numbered table embedded in STAR Methods?" },
  "star.embedded_figures": { row: 52, question: "Are there any figures in the STAR Methods?" },
  "resource.lead_contact": { row: 54, question: "More than one person listed or is NOT the LC?" },
  "resource.materials_availability": { row: 55, question: "Materials Availability Statement is missing/incomplete/unclear" },
  "resource.data_code_availability": { row: 56, question: "Data and Code Availability Statement” missing or not containing the 3 bullet points (Data/Code/Other)/standard wording?\"" },
  "data.accession_request": { row: 57, question: "Accession codes request" },
  "data.custom_code": { row: 58, question: "Unpublished custom code, software, or algorithm central to supporting the main claims of the paper is not archived in a publicly available repository and DOI or other unique identifier is NOT reported in STAR methods and KRT" },
  "data.separate_accession_section": { row: 59, question: "Accession codes for new data in different location?" },
  "data.accessions_not_in_krt": { row: 60, question: "Accession code/Software information provided here but not in the KRT" },
  "star.experimental_model": { row: 62, question: "Missing section; Missing institutional permission (IRC) info for higher vertebrate model or human subject studies; Missing sex/gender/both on  human/animal studies; Missing genotype and species/strain information for experimental model; Missing age/developmental stage of subject/experimental model" },
  "star.method_details": { row: 64, question: "Missing or thin (scarce information, mostly citations)" },
  "references.datasets_code_cited": { row: 65, question: "Datasets, program code, and methods used in the paper are not cited appropriately (using either a reference or a persistent identifier, or both)" },
  "star.quantification": { row: 67, question: "Missing/not detailed enough" },
  "star.clinical_trial": { row: 69, question: "Work is part of/involves a clinical trial" },
  "krt.present": { row: 71, question: "Missing?" },
  "krt.customized": { row: 72, question: "Merged cells/customized headings?" },
};

export const SPREADSHEET_PHRASES: Record<string, string> = {
  "file.word": `* For copyediting and typesetting purposes, the main document must be provided as a modifiable electronic file in a PC-compatible format (preferably a Word file). If your paper was created in LaTeX format, please include the following files: the main .pdf file, the .tex file, as well as all supporting files such as .bbl, .bib., .sty, .bst, etc.`,
  "title.length": `* For reasons of journal style and clarity, we would like to suggest a revision to the title. We would be happy to consider alternative suggestions - please ensure that the title does not exceed 15 words and does not contain punctuation.`,
  "summary.editor_edits": `* I have made minor edits to the Summary - please check them carefully.`,
  "summary.length": `* Please shorten the Summary to 150 words or fewer. The Summary should include the following elements: (1) a brief background of the question that avoids statements about how a process is not well understood; (2) a description of the results and approaches/model systems framed in the context of their conceptual interest; and (3) an indication of the broader significance of the work. We discourage novelty claims (e.g., use of the word “novel”) because they are overused, tend not to add meaning, and are difficult to verify. Please do not include references in the Summary.`,
  "sections.order": `* The main document must include the following sections (in this order): title, author list and affiliations, Lead Contact footnote, email address(es) of corresponding author(s), Summary, Introduction, Results, Discussion, Limitations of the Study, Acknowledgments, Author Contributions, Declaration of Interests, References, main figure titles and legends, main tables and legends, and supplemental video,data, and Excel table title and legends (as explained in detail in section C3 and C4). All Methods should be placed in STAR Methods section.`,
  "sections.limitations": `* Please include a paragraph entitled "Limitations of study" that highlights some potential caveats of the work.`,
  "body.novelty": `* We discourage novelty claims (e.g., use of the word “novel”) because they are overused, tend not to add meaning, and are difficult to verify.`,
  "body.results_subheadings": `* Please devide the Results section with subheadings. We recommend that you use similar language in your figure titles for clarity and structural harmony.`,
  "body.personal_communication": `* Unpublished data, submitted manuscripts, abstracts, and personal communications should be cited within the text only. Personal communication should be documented by a letter of permission (an e-mail is fine). Submitted articles should be cited as unpublished data, data not shown, or personal communication.`,
  "tables.format": `* Please use the Microsoft Word Table function to make tables; you may need to revise any tables that are not created using this function. Tables should include a title, and footnotes and/or legend should be concise. Include tables in the submitted manuscript as a separate section. Tables should not be separated into panels; i.e., they are numbered as Table 1, Table 2, etc., not as Table 1A, Table 1B, etc. Please do not include line breaks, merged cells, colors, shading, or tabs to separate data.`,
  "body.nomenclature": `* We require chemical nomenclature to conform to the standards set by IUPAC and other oversight organizations and gene nomenclature to conform to the standards set by HUGO, MGI, FlyBase, WormBase, SGI, and other oversight organizations. Please confirm that the content, capitalization, italicization, and style of the chemical and/or gene names within your paper are consistent with the rules set by one or more of these organizations.`,
  "associated.highlights": `* Please include the Highlights as per our guide to the authors. Highlights are bullet points that convey the core findings of your paper. You may include up to four highlights. The length of each highlight cannot exceed 85 characters (including spaces). On the EM page where you are asked to upload your files, please choose "Highlights" and upload as a Word document.`,
  "associated.graphical_abstract": `* Please submit a graphical abstract. A graphical abstract is an image that summarizes the main findings of a paper. It adds a rich, visual component to the start of a paper, helping readers to quickly appreciate and understand the central message. The image should be 1200 pixels square at 300 dpi, using Arial font with a size of 12–16 points; smaller fonts will not be legible online. Please refer to our graphical abstract guidelines (http://www.cell.com/pb/assets/raw/shared/figureguidelines/GA_guide.pdf) for more details and recommendations.`,
  "supplemental.figure_count": `* A comprehensive PDF should contain all supplemental figures and legends, supplemental schemes and legends (note that figures and schemes can be no longer than 1 page each), PDF-format supplemental tables, (in this order). The PDF should be considered ready for publication and should be uploaded with your final files. This text will not be copyedited. (Please see the Supplemental Guidelines for more detailed information.) (https://www.cell.com/star-supplemental-information). The supplemental PDF should not include the article title, author list, or affiliations (we will add a cover page with this information) or page numbers.`,
  "supplemental.related_to": `* Titles of all supplemental figures and items, including videos, tables, and schemes, should reference a main item (e.g., “Table S1. [Title], Related to Figure 1” or “Figure S3. [Title], Related to Figure 1 and Table 1”).`,
  "star.as_described_previously": `* In the methods, please avoid using "as described previously" and instead provide sufficient information such that the experiments could reasonably be reproduced without reference to other papers.`,
  "ethics.vertebrates": `* Please ensure a statement identifying the committee approving the experiments and confirming that all experiments conform to the relevant regulatory standards is included in the STAR Methods section. The sex of animal subjects and cells must be provided. In cases where this is appropriate, the influence (or association) of sex, gender, or both on the results of the study must be reported. Reporting of the age or developmental stage of subjects is also required.`,
  "ethics.humans": `* Please ensure that statements identifying the committee approving the studies and confirming that informed consent was obtained from all subjects must appear in the STAR Methods. The sex and gender, or both, must be reported for human subjects. In cases where this is appropriate, the influence (or association) of sex, gender, or both on the results of the study must be reported. Reporting of the age or developmental stage of subjects is also required.`,
  "references.entries": `* References should include only articles that are published or in press. For references to in-press articles, please confirm with the cited journal that the article is in fact accepted and in press, and include a DOI number and online publication date. Unpublished data, submitted manuscripts, abstracts, and personal communications should be cited within the text only. Personal communication should be documented by a letter of permission (an e-mail is fine). Submitted articles should be cited as unpublished data, data not shown, or personal communication. Article references should include the author list, year, article title, journal abbreviation, volume, page range, and DOI. (For references to articles that have only published online in advance of their issue’s publication, an online publication date and a DOI number must be provided. There should be a single Reference list. No references are allowed in Supplementary methods.
References must be cited by superscript numbers running consecutively in the text, e.g., "Multiple reports support this observation1,2" or "This observation is supported by Smith et al.1".`,
  "statements.acknowledgments": `* Please supply an acknowledgements section after the Methods section.`,
  "statements.author_contributions": `* Please supply an author contributions section after the Limitations of the Study section.`,
  "statements.declaration_of_interests": `* Please make a statement of declaration of interest interests after the acknowledgements section. Please fill and upload our Declaration of Interest form http://www.cell.com/pb/assets/raw/shared/forms/di_form.pdf`,
  "figures.separate_files": `* Please supply figures as separate files with high resolution. Please refer to our guidelines (https://www.cell.com/iscience/figureguidelines).`,
  "figures.error_bars": `* For any figures presenting pooled data and/or error bars, the measures should be defined in the figure legends. For example, “Data are represented as mean +/- SEM.`,
  "figures.asterisks": `* Where statistical tests are presented as asterisks, please ensure that the asterisks are defined in each relevant figure legend, together with the name of the statistical test.  This information should also go in the STAR Methods under QUANTIFICATION AND STATISTICAL ANALYSIS paragraph.`,
  "figures.scale_bars": `* Please ensure that at least one micrograph in each equivalent group in each figure is supplied with a representative scale bar, whose length is stated in the corresponding figure legend.`,
  "figures.blot_markers": `* Please ensure that all blots and gels are accompanied by the locations of molecular weight/size markers. Blots should be cropped such that at least one marker position is present.`,
  "data.supplementary_software": `* Please add details in the "Data and Code Availability" paragraph, in the "Resource Availability" section. This information should appear in the KRT as well.`,
  "data.structures": `* Please ensure that all structures are deposited in a publicly accessible database, and that accession codes are provided in the Key Resource Table and referred to in the "Data and Code Availability" subsection of the "Resource Availability" section.`,
  "data.gene_sequences": `* Please ensure that all novel gene sequences are deposited in a publicly accessible database, and that accession codes are provided in the Key Resource Table and referred to in the "Data and Code Availability" subsection of the "Resource Availability" section.`,
  "data.proteomics": `* Please ensure that all novel proteomic are deposited in a publicly accessible database, and that accession codes are provided in the Key Resource Table and referred to in the "Data and Code Availability" subsection of the "Resource Availability" section.`,
  "data.microarray": `* Please ensure that all novel microarray data are deposited in a publicly accessible database, and that accession codes are provided in the Key Resource Table and referred to in the "Data and Code Availability" subsection of the "Resource Availability" section.`,
  "data.rnaseq": `* Please ensure that all novel RNA-seq are deposited in a publicly accessible database, and that accession codes are provided in the Key Resource Table and referred to in the "Data and Code Availability" subsection of the "Resource Availability" section.`,
  "body.novel_compounds": `* Please see our requirements regarding characterization of novel chemical compounds: https://www.cell.com/iscience/authors`,
  "body.equations": `* Equations should be created with MathType. We will also accept equations created using Microsoft Word's Equation Editor. However, MathType is preferable due to some of Equation Editor’s limitations around version compatibility and editing.`,
  "supplemental.excel_tables": `* Supplemental tables exceeding 3 pages in length should instead be provided as individual Excel files. If necessary for organization, supplemental Excel tables may include tabs. Descriptive titles, including “Related to” information (mandatory), and legends (optional) for Excel-format tables should be included in the main document, after the figure legends.`,
  "supplemental.videos": `* Supplemental Videos should be uploaded as separate files in .mov, .avi., mpg., or .mp4 format and should meet the specifications listed under “Multimedia Files” in the Supplemental Guidelines. Descriptive titles, including “Related to” information (mandatory), and legends (optional) for Supplemental Videos should be included in the main document, after the figure legends. (Please note that videos may not be viewable at specifications other than those described in the link above.)`,
  "associated.star_protocols": `* Consider submitting one of your protocols to STAR Protocols, the new protocols journal from Cell Press. STAR Protocols aims to make the daily work of the scientific researcher easier by providing complete and consistent instructions on how to conduct experiments. STAR Protocols gives scientists the space they need to explain what worked and, perhaps more importantly, what didn't. The primary criteria for publication in STAR Protocols is usability and reproducibility. You can check out their most recent protocols here. If would like to submit your Protocol, please visit their submissions site. If you have any questions, please email starprotocols@cell.com.`,
  "statements.inclusion_diversity": `* Please make sure you use the information provided in the inclusion and diversity form (https://els-jbs-prod-cdn.jbs.elsevierhealth.com/pb/assets/raw/shared/forms/IandDstatement_form.pdf). Please find more information on this here, and preview the form here(https://www.cell.com/inclusion-diversity-statement-faqs).`,
  "body.batteries_pv": `* Please fill in the relevant checklist here: (batteries) https://www.cell.com/pb-assets/journals/research/joule/Checklist_Batteries_v1_(006)-1608320062.pdf; (PV) https://marlin-prod.literatumonline.com/pb-assets/journals/research/joule/multimedia_files-CP_PhotovoltaicChecklist.pdf`,
  "body.devices": `* All papers discussing new devices will need to feature results for all devices which were produced during the work (at least three, and certainly more than a "best device" example) and to have at least means and standard deviation of their performance.`,
  "star.present": `* Please include a STAR Methods section. STAR Methods follows a standardized structure including these specific headings in the following order: RESOURCE AVAILABILITY; EXPERIMENTAL MODEL AND SUBJECT DETAILS (*Please omit this section if your study does not use experimental models typical in the life sciences (e.g., if your study is computational or physical science research); METHOD DETAILS; QUANTIFICATION AND STATISTICAL ANALYSIS; ADDITIONAL RESOURCES. The list below details the information that should be reported in each section. Please see the STAR Methods guide for more information or contact me for help. Detailed formatting instructions at: https://marlin-prod.literatumonline.com/pb-assets/journals/research/cell/methods/Methods%20Guide_general.pdf`,
  "star.headings_order": `* STAR Methods follows a standardized structure. Please include these specific headings in the following order: RESOURCE AVAILABILITY; EXPERIMENTAL MODEL AND SUBJECT DETAILS (*Please omit this section if your study does not use experimental models typical in the life sciences (e.g., if your study is computational or physical science research); METHOD DETAILS; QUANTIFICATION AND STATISTICAL ANALYSIS; ADDITIONAL RESOURCES. The list below details the information that should be reported in each section. Please see the STAR Methods guide for more information or contact me for help. Detailed formatting instructions at: https://marlin-prod.literatumonline.com/pb-assets/journals/research/cell/methods/Methods%20Guide_general.pdf`,
  "star.subheadings": `* Please organize this section so it is easy for the reader to appreciate the different models/experiments/analyses used. Subheadings may be used here to help organize the information (up to two levels of subheadings are permitted), but numbering is not allowed.`,
  "star.references_in_lieu": `* References may be cited but cannot be used in lieu of reporting details of methods or analyses used. Please provide sufficient information on methods and analyses so that readers do not need to consult the cited papers to understand how the methods and analyses were conducted.`,
  "star.separate_reference_list": `* References cited in STAR Methods should be noted in the References list from the main text. Please combine the references from the STAR Methods with the References from the main text.`,
  "star.complex_tables": `* Tables that are complex in structure (i.e., split cells, shading, or multiple levels for organization) or exceed one page in length cannot be embedded in line with the STAR Methods text. Please include the table describing XXXXX as a supplemental table.`,
  "star.numbered_tables": `* We are not able to number tables embedded in STAR Methods text. Please retitle Table XXXXX and the references to it accordingly.`,
  "star.embedded_figures": `* We are not able to publish figures embedded within STAR Methods. Please remove the figure of XXXXX from the STAR Methods section and include it as a supplemental figure or contact me to discuss how to proceed.`,
  "resource.lead_contact": `* We require identification and contact information for a Lead Contact, who is the main point of contact for responding to material and resource requests. Please provide the full name and email address for the author taking responsibility for the Lead Contact role in the Lead Contact and Materials Availability section. Sample text to include: Further information and requests for resources and reagents should be directed to and will be fulfilled by the Lead Contact, XY (XY@qwerty.com).`,
  "resource.materials_availability": `* For publication we will require a “Materials Availability Statement” for all research papers in the STAR Methods section under the heading Lead Contact and Materials Availability even if no reagents were generated in the study. Examples of the types of appropriate “Materials Availability Statements” are below. A combination of these Statements may be appropriate. Plasmids generated in this study have been deposited to [Addgene, name and catalog number or unique identifier]; Mouse lines generated in this study have been deposited to [the Knockout Mouse Project (KOMP), name and catalog number or unique identifier]; This study did not generate new unique reagents; There are restrictions to the availability of [reagent] due to [REASON WHY RESTRICTIONS EXIST].`,
  "resource.data_code_availability": `* Please add details in the "Data and Code Availability" paragraph, in the "Resource Availability" section, in a structured form: a bullet point for Data, one for Code, one for all other items. Accession codes for this information should appear in the KRT. More information and examples of acceptable statements and approved repositories are at https://marlin-prod.literatumonline.com/pb-assets/journals/research/cell/methods/Methods_Guide_general.pdf`,
  "data.accession_request": `* Accession code request - As the manuscript generates datasets that are required to be available through a community-endorsed repository (i.e., DNA and protein sequences, structures of biological macromolecules, microarray data, RNAseq). Examples of the appropriate public repositories are found in the Mandatory Data Deposition section of Information for Authors (https://www.cell.com/cell/authors). Please include a statement describing the availability of datasets/code associated with the paper, including any conditions for access of datasets not publicly available.`,
  "data.custom_code": `* If the paper reports previously unpublished custom code, software, or algorithm that is central to supporting the main claims of the paper, this must be stated in the STAR Methods in the “Data and Code Availability” section and the Key Resources Table. A unique identifier must be provided. Please include any accession numbers, DOIs or unique identifiers, or web links to deposited datasets and code.  If URLs or links are provided in supplemental files, please report the supplemental file name (i.e., Table S1 if the information is reported in a supplemental table or Data S1 if the data is provided as part of the Supplemental Information PDF or compiled in a standalone ZIP file [which must be < 150MB]) For raw data at repositories that are Force11 compliant (i.e., Mendeley Data), please provide the DOI.`,
  "data.separate_accession_section": `* You currently have a separate accession code section. Please remove this and list the relevant accession codes in Data and Code Availability and under Deposited Data in the Key Resources Table`,
  "data.accessions_not_in_krt": `* Please note that we have updated our policy around Data and Code reporting. The accession codes should be reported in the Key Resources Table and referenced in the ""Data and Code availability"" section. EXAMPLE: ""• [Standardized datatype] data have been deposited at [datatype-specific repository] and are publicly available as of the date of publication. Accession numbers are listed in the key resources table."" For more information please follow the link https://marlin-prod.literatumonline.com/pb-assets/journals/research/cell/methods/Methods_Guide_general.pdf"`,
  "star.experimental_model": `* Please list here under separate headings all the experimental models (animals, human subjects, plants, microbe strains, cell lines, primary cell cultures) used in the study. For each model, provide information related to their species, genotype, age/developmental stage, maintenance, and care, including institutional permission and oversight information for the studies the experimental animal/human study. In cases where this is appropriate, the influence (or association) of sex, gender, or both on the results of the study must be reported.`,
  "star.method_details": `* The new STAR Methods format is not constrained by text limits, and we encourage authors to use this new structure to clearly describe how and why procedures or analyses were conducted. The current information does not provide sufficient information to make it clear how experiments/analyses were conducted. In particular, please expand the section detailing XXXXX. While citations may be used in STAR Methods, the methodological information critical for performing the experiments and analysis should be described with more detail in the Method Details section.`,
  "references.datasets_code_cited": `* All datasets, program code, and methods used in your manuscript must be appropriately cited in the text and listed in the reference section, either in the form of the publications where they were first reported or in the form of independent persistent identifiers such as the Digital Object Identifier (DOI).  When a dataset, program code, or method has a persistent identifier independent from the original study where it is first reported, we encourage you to cite both that identifier and the original study.  Please see the References section in our Information for Authors, How to Prepare and Submit Research Articles, for details on how references should be presented.`,
  "star.quantification": `* Please describe all of the statistical analyses and software used in this section and indicate where all of the statistical details of experiments can be found (e.g., in the figure legends, figures, Results, etc.), including the statistical tests used, exact value of n, what n represents (e.g., number of animals, number of cells, etc.), definition of center, and dispersion and precision measures (e.g., mean, median, SD, SEM, confidence intervals).`,
  "star.clinical_trial": `* As the work is part of/involves a clinical trial, please disclose any clinical registry number and associated links in the Additional Resources section.`,
  "krt.present": `* You do not currently have a Key Resources Table (KRT). The KRT highlights key reagents and resources used in the paper. The table need not list every item used or generated in the study and does not replace the detailed explanation of the methods and materials used in the study in the STAR Methods text. For details, please refer to the Table Template (http://www.cell.com/pb-assets/journals/research/cell/methods/table-template1.docx) or feel free to ask me for help.`,
  "krt.customized": `* We are not able to accommodate merged cells or customization of headings. Please list only one item per line and follow the heading structure and order provided in the Table Template (http://www.cell.com/pb-assets/journals/research/cell/methods/table-template1.docx).`,
};

/**
 * Phrases for FFC rules that have no row in the spreadsheet. Written in the same
 * register as the spreadsheet phrases and quoting the FFC wording where possible.
 */
export const FFC_PHRASES: Record<string, string> = {
  "title.lead_contact_footnote": "* All manuscripts must indicate a Lead Contact on the title page. The Lead Contact should be designated with a footnote in the author list, and must match the Lead Contact named in the Resource Availability section.",
  "title.corresponding_email": "* An email address should be included for each corresponding author on the title page.",
  "summary.heading": "* Please retitle the abstract section \"Summary\", as per journal style. The Summary should consist of a single paragraph of 150 words or fewer.",
  "resource.section": "* The manuscript must include a section titled \"Resource Availability\" with the following three subheadings: \"Lead Contact\", \"Materials Availability\" and \"Data and Code Availability\". Each subheading should be followed by a statement, as described in our Information for Authors.",
  "references.in_text": "* References must be cited by superscript numbers running consecutively in the text, e.g., \"Multiple reports support this observation1,2\" or \"This observation is supported by Smith et al.1\".",
  "references.in_press": "* References should include only articles that are published or in press. Unpublished data, submitted manuscripts, abstracts, and personal communications should be cited within the text only.",
  "figures.legends_list": "* Please include the main figure titles and legends as one list after the Declaration of Interests, not interspersed within the text, and do not include the main figures or schemes in the main document. Figures are required to include a descriptive title (e.g., Figure 1. [Title]).",
  "figures.see_also": "* Figure, table, and scheme legends should reference any related supplemental figures or items if applicable. For example, the end of the Figure 1 legend might say, \"See also Figure S1 and Table S1.\"",
  "statements.ai_declaration": "* If generative AI and/or AI-assisted technology was used in the writing process, please disclose this in a new section after the \"Declaration of Interests\" section, entitled \"Declaration of generative AI and AI-assisted technologies in the manuscript preparation process\" (example statement: \"During the preparation of this work the author(s) used [NAME TOOL / SERVICE] in order to [REASON]. After using this tool/service, the author(s) reviewed and edited the content as needed and take(s) full responsibility for the content of the publication.\")",
};

/** All iScience phrases by check-id suffix. */
export const ISCIENCE_PHRASES: Record<string, string> = { ...SPREADSHEET_PHRASES, ...FFC_PHRASES };
